// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    DropdownItem: typeof import('./components/DropdownItem.vue')['default']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    Headbar: typeof import('./components/Headbar.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}

export { }
